/* 
 * anytun version info 
 * 
 * this file was created automatically 
 * do not edit this file directly 
 * use win32/make_version_h.bat instead 
 */ 
 
#ifndef ANYTUN_version_h_INCLUDED 
#define ANYTUN_version_h_INCLUDED 
 
#define VERSION_STRING_0 " version trunk" 
#define VERSION_STRING_1 "built on XTREME-2S1FE8TO, 23.01.2013  1:42:54,89" 
 
#endif 
